### PR TITLE
Decouple p[l]otting

### PR DESCRIPTION
**Pull request by gkiar**
I began to address #3 . In particular, this PR already:

* Modularizes the codebase, separating out core elements like constants, the learner dataclass, plotting, and sorting functionality.
* Creating additional runscript for plotting.

It does not yet:

* Provide the added plotting functionality for degrading learners that is still within the notebook
* Provide a progress bar for degrading learner analysis
* Support any sort of configurability on how to define X or y variables (currently just pulls a fixed list from `core.constants`

### CODE REVIEW

**Comment by gkiar** [comment]
@nx10 @ReinderVosDeWael what do I need to do to make the `mypy` and `black` tests pass? I am not surprised about `unit` failing, since I don't have tests :)

**Comment by gkiar** [comment]
@nx10 @ReinderVosDeWael any ideas how to fix the testing errors?

* `unit` is no surprise since I don't have tests 🙂 
* `black` seems to want to make changes, but I don't know the flag to use when running it to make it do those replacements. Also, I posted this in slack, but it seems that `ruff` isn't auto-formatting my code which may solve this in future?
* The `mypy` error seems seriously odd and I've got no clue :) 

thanks!

**Comment by nx10** [comment]
Looks like you don't have any dependencies listed in your `project.toml` - did you forget to `poetry add` them?

**Comment by gkiar** [comment]
Ah, yes, I indeed did not add them via poetry, but was using pip :) I'll try to resolve that and see how that goes.... Still not really using poetry properly, I'm sure

**Comment by nx10** [comment]
For the tests I usually initially add this dummy:

https://github.com/childmindresearch/eeg_fmri_cleaning/blob/71158f05a05a7820b270656c1a7d3df9e386b1f7/tests/test_functions.py

That way the CI passes, and codecov will still shame me by showing 0% 😄

**Comment by gkiar** [comment]
Thanks! @nx10 if you can review to help me figure out why mypy and unit still aren't passing (despite seeming fine locally), that would be awesome.

@agoharzad if you can review the content of the PR more substantively, and let me know if you have any feedback on the overall logic of what I've got coded here, that'd be just as awesome.

Thanks, both!

**Comment by nx10** [comment]
The type of a numpy array is `np.ndarray`, not `np.array` (that one is actually a function), but I'm curious why mypy does not seem to run properly locally...

Will look at it more in-depth tomorrow or monday 👍

**Comment by ReinderVosDeWael** [comment]
mypy works fine for me locally - all mypy errors seem related to faulty definitions of numpy ND arrays as Florian mentioned earlier.

**Comment by gkiar** [comment]
So I just fixed the `np.array` → `np.ndarray` issue; but mypy still fails on GH? Any ideas? Thanks :)

**Comment by gkiar** [comment]
Yayy! Thank you @nx10 and @ReinderVosDeWael for your herculean effort in teaching me things. @agoharzad it _should_ be ready for scientific context review now

**Review by agoharzad — APPROVED** [review]

**Pull request merged**
